/****************************************************************************
*   Generated by ACUITY 6.30.0
*   Match ovxlib 1.1.53
*
*   Neural Network appliction post-process header file
****************************************************************************/
#ifndef _VNN_POST_PROCESS_H_
#define _VNN_POST_PROCESS_H_


// Ensemble post-processing function
vsi_status vnn_PostProcessAntiSpoofing(
    vsi_nn_graph_t *graph_v1se,
    vsi_nn_graph_t *graph_v2
);

const vsi_nn_postprocess_map_element_t * vnn_GetPostProcessMap();

uint32_t vnn_GetPostProcessMapCount();

#endif
